version: "3.2"
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - default
  api:
    build: ../backend-octopus/
    volumes:
     - ../backend-octopus/database:/app/database
    ports:
      - "5500:5500"
    networks:
      - default
    command: >
      sh -c "node built/main"

networks:
  default:
    driver: bridge
  
