const actionNames = [
  'TEST_ONLY',

  'IDENTIFY',

  'LOGIN',
  'LOGOUT',
  'SIGNUP',

  'SETUP_USER',

  'UPDATE_USER',
  'QUERY_USER_INFOMATION_WITH_EMAIL',
  'CHANGE_PASSWORD',

  'ADD_TODO',
  'UPDATE_TODO',
  'GET_TODOLIST',
  'GET_TODOBOXS',
  'ADD_TODOBOX',
  'DESTORY_TODO',

  'GET_TASK_BOARD',
  'GET_TASK_ALL_BOARD',
  'ADD_TASK_BOARD',
  'UPDATE_TASK_BOARD',
  'UPLOAD_TASK_BOARD_COVER',
  'DESTORY_TASK_BOARD',
  'TASKBOARD_SETTING_UPDATE',

  'ADD_TASK_TRACK',
  'GET_TASK_TRACK_CARD',
  'UPDATE_TASK_TRACK',
  'UPDATE_TASK_TRACK_INDEX',
  'DESTORY_TASK_TRACK',

  'GET_CARD_DETAIL',
  'ADD_TASK_CARD',
  'UPDATE_TASK_CARD',
  'DESTORY_TASK_CARD',
  'CARD_MOVE',
  'CARD_MOVE_HANDLE',

  'GET_TASK_BOARD_PARTICIPANT',
  'INVITE_TASK_BOARD_PARTICIPANT'
];

export default actionNames;
