export const actionNames = [
  'TEST_ONLY',

  'LOGIN',
  'LOGOUT',
  'SIGNUP',

  'SETUP_USER',

  'UPDATE_USER',
  'QUERY_USER_INFOMATION_WITH_EMAIL',
  'CHANGE_PASSWORD',

  'GET_CARD_DETAIL',
  'ADD_TASK_CARD',
  'ARCHIVE_TASK_CARD',
  'UPDATE_TASK_CARD',
  'DESTORY_TASK_CARD',
  'CARD_MOVE',
  'CARD_MOVE_HANDLE',

  'GET_TASK_BOARD_PARTICIPANT',
  'INVITE_TASK_BOARD_PARTICIPANT'
];

export default actionNames;
