export App from './App'
export Home from './Home'
export Home2 from './Home2'
export Foo from './Foo'
export Bar from './Bar'
export Login from './Login'
export SignUp from './sign-up'
export Tasks from './Tasks'
export TaskWall from './TaskWall'
export NotFound from './NotFound'
export DashBoard from './DashBoard'
export Setting from './Setting'
export Profile from './Profile'

export Loading from './util/loading'
