export App from './App'
export Login from './Login'
export SignUp from './SignUp'
export Tasks from './Tasks'
export TaskWall from './TaskWall'
export NotFound from './NotFound'
export DashBoard from './DashBoard'
export Setting from './Setting'
export Profile from './Profile'
export IndexPage from './IndexPage'

export Loading from './util/loading'
